language: ruby
rvm:
  - 2.2.1
  - rbx
services:
  - postgresql
# before_script:
#   - psql -c 'create database travis_ci_test;' -U postgres
#   - cp config/database.yml.travis config/database.yml
# test:
#   adapter: postgresql
#   database: travis_ci_test
#   username: postgres